---
# Minimal upstart service setup

- name: Create upstart config file
  ansible.builtin.template:
    src: kubesolo.upstart.j2
    dest: /etc/init/kubesolo.conf
    mode: '0644'
  become: true

- name: Start kubesolo service
  ansible.builtin.service:
    name: kubesolo
    state: started
  become: true
  register: service_start
  failed_when: false
