---
- name: Create openrc service script
  ansible.builtin.template:
    src: kubesolo.openrc.j2
    dest: /etc/init.d/kubesolo
    mode: "0755"
  become: true

- name: Enable kubesolo service
  ansible.builtin.service:
    name: kubesolo
    enabled: true
  become: true

- name: Start kubesolo service
  ansible.builtin.service:
    name: kubesolo
    state: started
  become: true
