---
- name: Create sysvinit service script
  ansible.builtin.template:
    src: kubesolo.sysvinit.j2
    dest: /etc/init.d/kubesolo
    mode: '0755'
  become: true

- name: Enable kubesolo service (Debian)
  ansible.builtin.command: update-rc.d kubesolo defaults
  become: true
  changed_when: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Enable kubesolo service (RedHat)
  ansible.builtin.command: chkconfig kubesolo on
  become: true
  changed_when: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Start kubesolo service
  ansible.builtin.service:
    name: kubesolo
    state: started
  become: true
